Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
Exception on / [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 24, in top-level template code
    <a href="{{ url_for('login') }}">Вход</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 24, in top-level template code
    <a href="{{ url_for('login') }}">Вход</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 24, in top-level template code
    <a href="{{ url_for('login') }}">Вход</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
Exception on / [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/templates/home.html", line 9, in block 'content'
    <a href="{{ url_for('register') }}" class="btn primary">Открыть счёт</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/templates/home.html", line 9, in block 'content'
    <a href="{{ url_for('register') }}" class="btn primary">Открыть счёт</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/templates/home.html", line 9, in block 'content'
    <a href="{{ url_for('register') }}" class="btn primary">Открыть счёт</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
Exception on / [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/templates/home.html", line 9, in block 'content'
    <a href="{{ url_for('register') }}" class="btn primary">Открыть счёт</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
Exception on / [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 35, in top-level template code
    <p>© 2025 Bank Comfort — лидер среди онлайн-банков. <a href="{{ url_for('support') }}">Поддержка</a></p>
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'support'. Did you mean 'main.support' instead?
Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
User 2 logged in (session set)
Exception on / [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 17, in top-level template code
    <a href="{{ url_for('dashboard') }}">Панель</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard'. Did you mean 'main.dashboard' instead?
Exception on /auth/register [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/auth.py", line 48, in register
    return render_template("register.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/register.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 17, in top-level template code
    <a href="{{ url_for('dashboard') }}">Панель</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard'. Did you mean 'main.dashboard' instead?
Exception on /auth/login [GET]
Traceback (most recent call last):
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/routes/auth.py", line 21, in login
    return render_template("login.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/opt/bankapp/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/bankapp/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/bankapp/templates/base.html", line 17, in top-level template code
    <a href="{{ url_for('dashboard') }}">Панель</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bankapp/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard'. Did you mean 'main.dashboard' instead?
2025-10-13 23:17:33,440 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-13 23:17:33,446 [INFO] app: Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
2025-10-13 23:17:33,974 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.33.0.2:5000
2025-10-13 23:17:33,975 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-10-13 23:17:37,501 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:37] "GET / HTTP/1.1" 200 -
2025-10-13 23:17:37,549 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:37] "[33mGET /static/styles.css HTTP/1.1[0m" 404 -
2025-10-13 23:17:37,994 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:37] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-10-13 23:17:54,935 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:54] "GET / HTTP/1.1" 200 -
2025-10-13 23:17:54,979 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:54] "[33mGET /static/styles.css HTTP/1.1[0m" 404 -
2025-10-13 23:17:56,480 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:56] "GET /auth/login HTTP/1.1" 200 -
2025-10-13 23:17:56,580 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:56] "[33mGET /static/styles.css HTTP/1.1[0m" 404 -
2025-10-13 23:17:58,100 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:58] "GET /auth/register HTTP/1.1" 200 -
2025-10-13 23:17:58,196 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:58] "[33mGET /static/styles.css HTTP/1.1[0m" 404 -
2025-10-13 23:17:58,906 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:58] "GET / HTTP/1.1" 200 -
2025-10-13 23:17:58,951 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:17:58] "[33mGET /static/styles.css HTTP/1.1[0m" 404 -
2025-10-13 23:26:14,728 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-13 23:26:14,733 [INFO] app: Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
2025-10-13 23:26:15,258 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.33.0.2:5000
2025-10-13 23:26:15,259 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-10-13 23:26:23,054 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:26:23] "GET / HTTP/1.1" 200 -
2025-10-13 23:26:23,130 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:26:23] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-13 23:26:23,134 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:26:23] "GET /static/js/app.js HTTP/1.1" 200 -
2025-10-13 23:26:23,178 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:26:23] "GET /static/js/app.js HTTP/1.1" 200 -
2025-10-13 23:26:23,203 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:26:23] "GET /static/img/favicon.ico HTTP/1.1" 200 -
2025-10-13 23:27:52,375 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:27:52] "GET / HTTP/1.1" 200 -
2025-10-13 23:27:52,419 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:27:52] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:27:52,419 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:27:52] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-13 23:27:52,498 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:27:52] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:27:56,646 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:27:56] "GET /auth/register HTTP/1.1" 200 -
2025-10-13 23:27:56,674 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:27:56] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:27:56,674 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:27:56] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:27:56,782 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:27:56] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:28:12,283 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:28:12] "GET / HTTP/1.1" 200 -
2025-10-13 23:28:12,325 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:28:12] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:28:12,325 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:28:12] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:28:12,391 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:28:12] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:09,150 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:09] "GET / HTTP/1.1" 200 -
2025-10-13 23:31:09,191 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:09] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:09,191 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:09] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-13 23:31:09,235 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:09] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:17,977 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:17] "GET / HTTP/1.1" 200 -
2025-10-13 23:31:18,010 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:18] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:31:18,011 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:18] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:18,059 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:18] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:21,280 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-13 23:31:21,285 [INFO] app: Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
2025-10-13 23:31:21,822 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.33.0.2:5000
2025-10-13 23:31:21,822 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-10-13 23:31:23,112 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:23] "GET / HTTP/1.1" 200 -
2025-10-13 23:31:23,146 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:23] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:31:23,156 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:23] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:23,181 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:23] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:24,837 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:24] "GET /auth/register HTTP/1.1" 200 -
2025-10-13 23:31:24,875 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:24] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:31:24,876 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:24] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:24,895 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:24] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:25,636 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:25] "GET /auth/login HTTP/1.1" 200 -
2025-10-13 23:31:25,678 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:25] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:31:25,678 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:25] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:25,698 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:25] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:27,547 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:27] "GET /auth/login HTTP/1.1" 200 -
2025-10-13 23:31:27,590 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:27] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:31:27,590 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:27] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:27,657 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:27] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:28,265 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:28] "GET /auth/register HTTP/1.1" 200 -
2025-10-13 23:31:28,308 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:28] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:31:28,309 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:28] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:28,373 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:28] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:28,567 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:28] "GET /auth/login HTTP/1.1" 200 -
2025-10-13 23:31:28,606 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:28] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:31:28,607 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:28] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:31:28,704 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:31:28] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:32:04,792 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:04] "GET / HTTP/1.1" 200 -
2025-10-13 23:32:04,831 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:04] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-13 23:32:04,833 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:04] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:32:04,951 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:04] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:32:05,783 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:05] "GET / HTTP/1.1" 200 -
2025-10-13 23:32:05,818 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:05] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:32:05,818 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:05] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:32:05,887 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:05] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:32:15,585 [ERROR] app: Exception on /support [GET]
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/routes/main.py", line 23, in support
    return render_template("support.html")
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/support.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/support.html", line 34, in block 'content'
    <form method="post" action="{{ url_for('support') }}">
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'support'. Did you mean 'main.support' instead?
2025-10-13 23:32:15,588 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:15] "[35m[1mGET /support HTTP/1.1[0m" 500 -
2025-10-13 23:32:17,309 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:17] "GET /about HTTP/1.1" 200 -
2025-10-13 23:32:17,343 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:17] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:32:17,344 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:17] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:32:17,448 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:17] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:32:17,449 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:17] "GET /static/img/team_ceo.jpg HTTP/1.1" 200 -
2025-10-13 23:32:17,449 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:17] "GET /static/img/team_cto.jpg HTTP/1.1" 200 -
2025-10-13 23:32:17,450 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:17] "GET /static/img/team_ciso.jpg HTTP/1.1" 200 -
2025-10-13 23:32:23,615 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:23] "[33mGET /static/docs/privacy_policy.pdf HTTP/1.1[0m" 404 -
2025-10-13 23:32:25,282 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:32:25] "[33mGET /static/docs/terms.pdf HTTP/1.1[0m" 404 -
2025-10-13 23:35:57,306 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:35:57] "GET / HTTP/1.1" 200 -
2025-10-13 23:35:57,349 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:35:57] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:35:57,349 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:35:57] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-13 23:35:57,376 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:35:57] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:39:07,169 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:07] "GET / HTTP/1.1" 200 -
2025-10-13 23:39:07,210 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:07] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-13 23:39:07,211 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:07] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:39:07,252 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:07] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:39:19,408 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-13 23:39:19,413 [INFO] app: Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
2025-10-13 23:39:19,973 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.33.0.2:5000
2025-10-13 23:39:19,973 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-10-13 23:39:21,016 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:21] "GET / HTTP/1.1" 200 -
2025-10-13 23:39:21,048 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:21] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:39:21,049 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:21] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:39:21,075 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:21] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:39:22,709 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:22] "GET /auth/register HTTP/1.1" 200 -
2025-10-13 23:39:22,781 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:22] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-13 23:39:22,783 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:22] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:39:22,803 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:39:22] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:41:19,201 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:41:19] "GET / HTTP/1.1" 200 -
2025-10-13 23:41:19,240 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:41:19] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-13 23:41:19,240 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:41:19] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-13 23:41:19,364 [INFO] werkzeug: 10.33.0.2 - - [13/Oct/2025 23:41:19] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:12:40,570 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:12:40] "GET / HTTP/1.1" 200 -
2025-10-14 00:12:40,611 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:12:40] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:12:40,611 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:12:40] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:12:40,628 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:12:40] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:13:03,819 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:03] "GET /about HTTP/1.1" 200 -
2025-10-14 00:13:03,861 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:13:03,861 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:03] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:13:03,905 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:03] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:13:03,907 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:03] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:13:03,908 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:03] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:13:03,908 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:03] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:13:18,286 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:18] "[33mGET /admin_panel HTTP/1.1[0m" 404 -
2025-10-14 00:13:28,236 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:28] "[33mGET /apply_card HTTP/1.1[0m" 404 -
2025-10-14 00:13:37,941 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:37] "[33mGET /cards HTTP/1.1[0m" 404 -
2025-10-14 00:13:46,949 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:46] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-10-14 00:13:46,968 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:46] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 00:13:47,005 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:47] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:13:47,006 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:47] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:13:47,133 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:47] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:13:55,418 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:13:55] "[33mGET /error HTTP/1.1[0m" 404 -
2025-10-14 00:14:02,675 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:02] "[33mGET /home HTTP/1.1[0m" 404 -
2025-10-14 00:14:10,446 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:10] "[33mGET /index HTTP/1.1[0m" 404 -
2025-10-14 00:14:15,380 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:15] "[33mGET /login HTTP/1.1[0m" 404 -
2025-10-14 00:14:23,643 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:23] "GET / HTTP/1.1" 200 -
2025-10-14 00:14:23,700 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:23] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:14:23,700 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:23] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:14:23,788 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:23] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:14:30,520 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:30] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 00:14:30,555 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:30] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:14:30,556 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:30] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:14:30,571 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:14:30] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:18:43,902 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:18:43] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 00:18:43,935 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:18:43] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:18:43,935 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:18:43] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:18:44,070 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:18:44] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:20:49,235 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:49] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 00:20:49,275 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:49] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:20:49,276 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:49] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:20:49,322 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:49] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:20:52,625 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:52] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 00:20:52,670 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:52] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:20:52,671 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:52] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:20:52,728 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:52] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:20:58,448 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:58] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 00:20:58,489 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:58] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:20:58,490 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:58] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:20:58,598 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:20:58] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:21:04,664 [ERROR] app: Exception on /support [GET]
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/routes/main.py", line 23, in support
    return render_template("support.html")
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/support.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/support.html", line 34, in block 'content'
    <form method="post" action="{{ url_for('support') }}">
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'support'. Did you mean 'main.support' instead?
2025-10-14 00:21:04,668 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:21:04] "[35m[1mGET /support HTTP/1.1[0m" 500 -
2025-10-14 00:21:07,352 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:21:07] "GET /about HTTP/1.1" 200 -
2025-10-14 00:21:07,394 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:21:07] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:21:07,395 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:21:07] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:21:07,420 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:21:07] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:21:07,467 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:21:07] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:21:07,467 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:21:07] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:21:07,468 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:21:07] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:22:23,310 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:22:23] "GET /about HTTP/1.1" 200 -
2025-10-14 00:22:23,346 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:22:23] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:22:23,346 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:22:23] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:22:23,402 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:22:23] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:22:23,440 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:22:23] "GET /static/img/team_ceo.jpg HTTP/1.1" 200 -
2025-10-14 00:22:23,441 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:22:23] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:22:23,442 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:22:23] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:24:52,263 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:24:52] "GET /about HTTP/1.1" 200 -
2025-10-14 00:24:52,310 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:24:52] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:24:52,311 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:24:52] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:24:52,343 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:24:52] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:24:52,362 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:24:52] "GET /static/img/team_ciso.jpg HTTP/1.1" 200 -
2025-10-14 00:24:52,363 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:24:52] "GET /static/img/team_cto.jpg HTTP/1.1" 200 -
2025-10-14 00:24:52,363 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:24:52] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:27:12,033 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:27:12] "GET /about HTTP/1.1" 200 -
2025-10-14 00:27:12,081 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:27:12] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:27:12,081 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:27:12] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:27:12,121 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:27:12] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:27:12,122 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:27:12] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:27:12,122 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:27:12] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:27:12,130 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:27:12] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:28:17,357 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:17] "GET / HTTP/1.1" 200 -
2025-10-14 00:28:17,404 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:17] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:28:17,408 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:17] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:28:17,464 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:17] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:28:19,883 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:19] "GET / HTTP/1.1" 200 -
2025-10-14 00:28:19,924 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:19] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:28:19,925 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:19] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:28:19,945 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:19] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:28:30,196 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:30] "GET /about HTTP/1.1" 200 -
2025-10-14 00:28:30,251 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:30] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:28:30,252 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:30] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:28:30,293 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:30] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:28:30,298 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:30] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:28:30,299 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:30] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:28:30,300 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:28:30] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:29:43,395 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:29:43] "GET / HTTP/1.1" 200 -
2025-10-14 00:29:43,444 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:29:43] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:29:43,445 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:29:43] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:29:43,458 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:29:43] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:32:28,495 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:28] "GET / HTTP/1.1" 200 -
2025-10-14 00:32:28,539 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:28] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:32:28,540 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:28] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:32:28,639 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:28] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:32:35,315 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:35] "GET /about HTTP/1.1" 200 -
2025-10-14 00:32:35,372 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:35] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:32:35,373 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:35] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:32:35,472 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:35] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:32:35,473 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:35] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:32:35,475 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:35] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:32:35,476 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:32:35] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:34:10,714 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:10] "GET / HTTP/1.1" 200 -
2025-10-14 00:34:10,744 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:10] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:34:10,745 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:10] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:34:10,801 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:10] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:34:47,174 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:47] "GET / HTTP/1.1" 200 -
2025-10-14 00:34:47,216 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:47] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:34:47,217 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:47] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:34:47,347 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:47] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:34:57,096 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:57] "GET /about HTTP/1.1" 200 -
2025-10-14 00:34:57,142 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:57] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:34:57,143 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:57] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:34:57,229 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:57] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:34:57,230 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:57] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:34:57,231 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:57] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:34:57,232 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:34:57] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:35:05,676 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:05] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 00:35:05,725 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:05] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:35:05,726 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:05] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:05,798 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:05] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:07,648 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:07] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 00:35:07,689 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:07] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:07,690 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:07] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:35:07,742 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:07] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:10,992 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:10] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 00:35:11,035 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:11] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:35:11,035 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:11] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:11,162 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:11] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:12,443 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:12] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 00:35:12,485 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:12] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:35:12,486 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:12] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:12,545 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:12] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:25,479 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:25] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 00:35:25,519 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:25] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:25,520 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:25] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:35:25,589 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:25] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:27,052 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:27] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 00:35:27,093 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:27] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:27,093 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:27] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:35:27,216 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:27] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:28,860 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:28] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 00:35:28,903 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:28] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:28,904 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:28] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:35:29,015 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:29] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:29,979 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:29] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 00:35:30,024 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:30] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:35:30,024 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:30] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:30,040 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:30] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:56,162 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:56] "GET /about HTTP/1.1" 200 -
2025-10-14 00:35:56,201 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:56] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:35:56,201 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:56] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:56,276 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:56] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:35:56,277 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:56] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:35:56,279 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:56] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:35:56,279 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:56] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:35:58,434 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:35:58] "[33mGET /static/docs/privacy_policy.pdf HTTP/1.1[0m" 404 -
2025-10-14 00:36:40,747 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:36:40] "GET / HTTP/1.1" 200 -
2025-10-14 00:36:40,808 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:36:40] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:36:40,809 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:36:40] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:36:40,857 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:36:40] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:39:42,953 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:42] "GET / HTTP/1.1" 200 -
2025-10-14 00:39:42,987 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:42] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:39:42,989 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:42] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:39:43,035 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:43] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:39:45,830 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:45] "GET / HTTP/1.1" 200 -
2025-10-14 00:39:45,861 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:45] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:39:45,862 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:45] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:39:45,966 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:45] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:39:47,408 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:47] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 00:39:47,501 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:47] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:39:47,502 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:47] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:39:47,571 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:47] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:39:50,122 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:50] "GET / HTTP/1.1" 200 -
2025-10-14 00:39:50,162 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:50] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:39:50,163 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:50] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:39:50,205 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:39:50] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:40:20,399 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:40:20] "GET / HTTP/1.1" 200 -
2025-10-14 00:40:20,433 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:40:20] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:40:20,434 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:40:20] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:40:20,563 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:40:20] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:40:21,165 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:40:21] "GET / HTTP/1.1" 200 -
2025-10-14 00:40:21,201 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:40:21] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:40:21,201 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:40:21] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:40:21,270 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:40:21] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:41:15,482 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:15] "GET / HTTP/1.1" 200 -
2025-10-14 00:41:15,527 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:15] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:41:15,528 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:15] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:41:15,594 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:15] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:41:31,377 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:31] "GET / HTTP/1.1" 200 -
2025-10-14 00:41:31,414 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:31] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:41:31,415 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:31] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:41:31,528 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:31] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:41:35,565 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:35] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 00:41:35,616 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:35] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:41:35,617 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:35] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:41:35,747 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:41:35] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:43:36,959 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:43:36] "GET / HTTP/1.1" 200 -
2025-10-14 00:43:37,010 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:43:37] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:43:37,011 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:43:37] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:43:37,027 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:43:37] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:43:37,952 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:43:37] "GET / HTTP/1.1" 200 -
2025-10-14 00:43:37,989 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:43:37] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:43:37,990 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:43:37] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:43:38,036 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:43:38] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:45:09,113 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:45:09] "GET / HTTP/1.1" 200 -
2025-10-14 00:45:09,155 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:45:09] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:45:09,156 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:45:09] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:45:09,203 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:45:09] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:45:09,233 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:45:09] "[33mGET /static/img/background.jpg HTTP/1.1[0m" 404 -
2025-10-14 00:45:26,466 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:45:26] "GET / HTTP/1.1" 200 -
2025-10-14 00:45:26,499 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:45:26] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:45:26,500 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:45:26] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:45:26,541 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:45:26] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:45:26,541 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:45:26] "GET /static/img/bank_bg.jpg HTTP/1.1" 200 -
2025-10-14 00:47:59,669 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:47:59] "GET / HTTP/1.1" 200 -
2025-10-14 00:47:59,718 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:47:59] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:47:59,718 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:47:59] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:47:59,745 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:47:59] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:47:59,760 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:47:59] "[36mGET /static/img/bank_bg.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:48:02,686 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:02] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 00:48:02,727 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:02] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:48:02,728 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:02] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:48:02,771 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:02] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:48:02,814 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:02] "[36mGET /static/img/bank_bg.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:48:08,284 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:08] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 00:48:08,332 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:08] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:48:08,332 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:08] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:48:08,427 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:08] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:48:08,438 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:08] "[36mGET /static/img/bank_bg.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:48:11,907 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:11] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 00:48:11,937 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:11] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:48:11,945 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:11] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:48:12,021 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:12] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:48:12,031 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:12] "[36mGET /static/img/bank_bg.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:48:17,724 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:17] "GET /about HTTP/1.1" 200 -
2025-10-14 00:48:17,776 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:17] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:48:17,777 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:17] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:48:17,782 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:17] "GET /static/img/team_ceo.jpg HTTP/1.1" 200 -
2025-10-14 00:48:17,782 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:17] "GET /static/img/team_cto.jpg HTTP/1.1" 200 -
2025-10-14 00:48:17,783 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:17] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:48:17,796 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:17] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:48:17,822 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:48:17] "[36mGET /static/img/bank_bg.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:49:35,965 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:35] "GET / HTTP/1.1" 200 -
2025-10-14 00:49:36,009 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:36] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:49:36,010 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:36] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:49:36,038 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:36] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:49:36,054 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:36] "[36mGET /static/img/bank_bg.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:49:40,613 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:40] "GET /about HTTP/1.1" 200 -
2025-10-14 00:49:40,662 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:40] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:49:40,663 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:40] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:49:40,708 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:40] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:49:40,709 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:40] "[36mGET /static/img/bank_bg.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:49:40,711 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:40] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:49:40,711 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:40] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:49:40,713 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:49:40] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:51:09,805 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:51:09] "GET /about HTTP/1.1" 200 -
2025-10-14 00:51:09,842 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:51:09] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:51:09,844 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:51:09] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:51:09,889 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:51:09] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:51:09,893 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:51:09] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:51:09,893 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:51:09] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:51:09,894 [INFO] werkzeug: 10.33.0.2 - - [14/Oct/2025 00:51:09] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:52:04,285 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-14 00:52:04,291 [INFO] app: Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
2025-10-14 00:52:04,301 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.105:5000
2025-10-14 00:52:04,302 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-10-14 00:52:10,881 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-14 00:52:10,885 [INFO] app: Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
2025-10-14 00:52:10,896 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.105:5000
2025-10-14 00:52:10,896 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-10-14 00:52:12,728 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:12] "GET / HTTP/1.1" 200 -
2025-10-14 00:52:12,799 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:12] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:52:12,799 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:12] "GET /static/js/app.js HTTP/1.1" 200 -
2025-10-14 00:52:12,866 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:12] "GET /static/img/logo.png HTTP/1.1" 200 -
2025-10-14 00:52:12,866 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:12] "GET /static/js/app.js HTTP/1.1" 200 -
2025-10-14 00:52:12,915 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:12] "GET /static/img/favicon.ico HTTP/1.1" 200 -
2025-10-14 00:52:31,922 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:31] "GET /about HTTP/1.1" 200 -
2025-10-14 00:52:31,975 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:31] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:52:31,975 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:31] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:52:32,031 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:32] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:52:32,057 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:32] "GET /static/img/team_ceo.jpg HTTP/1.1" 200 -
2025-10-14 00:52:32,058 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:32] "GET /static/img/team_cto.jpg HTTP/1.1" 200 -
2025-10-14 00:52:32,058 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:32] "GET /static/img/team_ciso.jpg HTTP/1.1" 200 -
2025-10-14 00:52:51,629 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:51] "GET /about HTTP/1.1" 200 -
2025-10-14 00:52:51,668 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:51] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:52:51,669 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:51] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:52:51,716 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:51] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:52:51,761 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:51] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:52:51,761 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:51] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:52:51,762 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:51] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:52:54,263 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:54] "GET / HTTP/1.1" 200 -
2025-10-14 00:52:54,314 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:54] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:52:54,315 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:54] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:52:54,397 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:54] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
2025-10-14 00:52:54,398 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:52:54] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:53:34,462 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:53:34] "GET / HTTP/1.1" 200 -
2025-10-14 00:53:34,499 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:53:34] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:53:34,500 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:53:34] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:53:34,545 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:53:34] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:53:34,568 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:53:34] "[33mGET /static/img/logo.png HTTP/1.1[0m" 404 -
2025-10-14 00:54:30,928 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-14 00:54:30,933 [INFO] app: Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
2025-10-14 00:54:30,943 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.105:5000
2025-10-14 00:54:30,943 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-10-14 00:54:32,803 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:54:32] "GET / HTTP/1.1" 200 -
2025-10-14 00:54:32,841 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:54:32] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:54:32,841 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:54:32] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:54:32,877 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:54:32] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:55:58,404 [INFO] werkzeug: 192.168.0.110 - - [14/Oct/2025 00:55:58] "GET / HTTP/1.1" 200 -
2025-10-14 00:55:58,433 [INFO] werkzeug: 192.168.0.110 - - [14/Oct/2025 00:55:58] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 00:55:58,436 [INFO] werkzeug: 192.168.0.110 - - [14/Oct/2025 00:55:58] "GET /static/js/app.js HTTP/1.1" 200 -
2025-10-14 00:55:58,512 [INFO] werkzeug: 192.168.0.110 - - [14/Oct/2025 00:55:58] "GET /static/img/favicon.ico HTTP/1.1" 200 -
2025-10-14 00:57:03,154 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:57:03] "GET /about HTTP/1.1" 200 -
2025-10-14 00:57:03,192 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:57:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 00:57:03,193 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:57:03] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:57:03,236 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:57:03] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 00:57:03,240 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:57:03] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:57:03,242 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:57:03] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 00:57:03,244 [INFO] werkzeug: 192.168.0.105 - - [14/Oct/2025 00:57:03] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 16:22:09,110 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-14 16:22:09,117 [INFO] app: Database initialized (url=sqlite:///./data/bankapp_dev.sqlite3, echo=False)
2025-10-14 16:22:09,127 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.105:5000
2025-10-14 16:22:09,127 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-10-14 16:22:50,501 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:22:50] "GET / HTTP/1.1" 200 -
2025-10-14 16:22:50,552 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:22:50] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 16:22:51,504 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:22:51] "GET /static/js/app.js HTTP/1.1" 200 -
2025-10-14 16:22:51,548 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:22:51] "GET /static/img/favicon.ico HTTP/1.1" 200 -
2025-10-14 16:22:53,934 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:22:53] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 16:22:53,979 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:22:53] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:22:53,983 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:22:53] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:23:03,909 [ERROR] app: Exception on /support [GET]
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/routes/main.py", line 23, in support
    return render_template("support.html")
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/support.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/support.html", line 34, in block 'content'
    <form method="post" action="{{ url_for('support') }}">
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'support'. Did you mean 'main.support' instead?
2025-10-14 16:23:03,914 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:03] "[35m[1mGET /support HTTP/1.1[0m" 500 -
2025-10-14 16:23:04,082 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:04] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-10-14 16:23:09,763 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:09] "GET /about HTTP/1.1" 200 -
2025-10-14 16:23:09,825 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:09] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:23:09,836 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:09] "GET /static/img/team_cto.jpg HTTP/1.1" 200 -
2025-10-14 16:23:09,837 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:09] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:23:09,838 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:09] "GET /static/img/team_ciso.jpg HTTP/1.1" 200 -
2025-10-14 16:23:09,838 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:09] "GET /static/img/team_ceo.jpg HTTP/1.1" 200 -
2025-10-14 16:23:22,883 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:22] "[33mGET /static/docs/privacy_policy.pdf HTTP/1.1[0m" 404 -
2025-10-14 16:23:27,711 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:27] "[33mGET /static/docs/terms.pdf HTTP/1.1[0m" 404 -
2025-10-14 16:23:34,342 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:34] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 16:23:34,403 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:34] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:23:34,406 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:34] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:23:36,202 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:36] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 16:23:36,253 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:36] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:23:36,257 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:23:36] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:24:23,304 [INFO] audit: {"ts": "2025-10-14T06:24:23.304205Z", "event": "user_registered", "source_ip": "192.168.0.101", "user": "SOCiSKA", "details": {"email": "huesos@gim.com"}}
2025-10-14 16:24:23,304 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:24:23] "[32mPOST /auth/register HTTP/1.1[0m" 302 -
2025-10-14 16:24:23,318 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:24:23] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 16:24:23,394 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:24:23] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:24:23,595 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:24:23] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:24:35,336 [INFO] app: User 3 logged in (session set)
2025-10-14 16:24:35,336 [INFO] audit: {"ts": "2025-10-14T06:24:35.336646Z", "event": "login_succeeded", "source_ip": "192.168.0.101", "user": "SOCiSKA", "details": "login ok"}
2025-10-14 16:24:35,337 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:24:35] "[32mPOST /auth/login HTTP/1.1[0m" 302 -
2025-10-14 16:24:35,351 [ERROR] app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/base.html", line 20, in top-level template code
    <a href="{{ url_for('dashboard') }}">Панель</a>
    ^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard'. Did you mean 'main.dashboard' instead?
2025-10-14 16:24:35,353 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:24:35] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-10-14 16:24:40,262 [ERROR] app: Exception on /auth/login [GET]
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/routes/auth.py", line 21, in login
    return render_template("login.html")
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/base.html", line 20, in top-level template code
    <a href="{{ url_for('dashboard') }}">Панель</a>
    ^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard'. Did you mean 'main.dashboard' instead?
2025-10-14 16:24:40,266 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:24:40] "[35m[1mGET /auth/login HTTP/1.1[0m" 500 -
2025-10-14 16:24:42,076 [ERROR] app: Exception on /auth/register [GET]
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/routes/auth.py", line 48, in register
    return render_template("register.html")
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/register.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/base.html", line 20, in top-level template code
    <a href="{{ url_for('dashboard') }}">Панель</a>
    ^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard'. Did you mean 'main.dashboard' instead?
2025-10-14 16:24:42,080 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:24:42] "[35m[1mGET /auth/register HTTP/1.1[0m" 500 -
2025-10-14 16:24:43,630 [ERROR] app: Exception on /about [GET]
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/routes/main.py", line 17, in about
    return render_template("about.html")
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/about.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/base.html", line 20, in top-level template code
    <a href="{{ url_for('dashboard') }}">Панель</a>
    ^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard'. Did you mean 'main.dashboard' instead?
2025-10-14 16:24:43,634 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:24:43] "[35m[1mGET /about HTTP/1.1[0m" 500 -
2025-10-14 16:25:05,820 [ERROR] app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/base.html", line 20, in top-level template code
    <a href="{{ url_for('dashboard') }}">Панель</a>
    ^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard'. Did you mean 'main.dashboard' instead?
2025-10-14 16:25:05,824 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:25:05] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-10-14 16:26:13,045 [ERROR] app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/routes/main.py", line 12, in index
    return render_template("home.html")
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/home.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/base.html", line 20, in top-level template code
    <a href="{{ url_for('dashboard') }}">Панель</a>
    ^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard'. Did you mean 'main.dashboard' instead?
2025-10-14 16:26:13,049 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:26:13] "[35m[1mGET / HTTP/1.1[0m" 500 -
2025-10-14 16:26:19,179 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:26:19] "[33mGET /base HTTP/1.1[0m" 404 -
2025-10-14 16:26:26,774 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:26:26] "[33mGET /index HTTP/1.1[0m" 404 -
2025-10-14 16:26:34,164 [ERROR] app: Exception on /about [GET]
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/routes/main.py", line 17, in about
    return render_template("about.html")
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/about.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/templates/base.html", line 20, in top-level template code
    <a href="{{ url_for('dashboard') }}">Панель</a>
    ^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'dashboard'. Did you mean 'main.dashboard' instead?
2025-10-14 16:26:34,167 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:26:34] "[35m[1mGET /about HTTP/1.1[0m" 500 -
2025-10-14 16:27:42,419 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:27:42] "GET /about HTTP/1.1" 200 -
2025-10-14 16:27:42,468 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:27:42] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:27:42,474 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:27:42] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 16:27:42,479 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:27:42] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 16:27:42,480 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:27:42] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 16:27:42,482 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:27:42] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:27:42,579 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:27:42] "[36mGET /static/img/favicon.ico HTTP/1.1[0m" 304 -
2025-10-14 16:27:51,611 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:27:51] "GET / HTTP/1.1" 200 -
2025-10-14 16:27:51,668 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:27:51] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:27:51,672 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:27:51] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:28:17,918 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:17] "GET / HTTP/1.1" 200 -
2025-10-14 16:28:17,947 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:17] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:28:17,953 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:17] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:28:22,181 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:22] "GET /auth/register HTTP/1.1" 200 -
2025-10-14 16:28:22,223 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:22] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:28:22,229 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:22] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:28:25,691 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:25] "GET /about HTTP/1.1" 200 -
2025-10-14 16:28:25,731 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:25] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:28:25,737 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:25] "[36mGET /static/img/team_ceo.jpg HTTP/1.1[0m" 304 -
2025-10-14 16:28:25,740 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:25] "[36mGET /static/img/team_cto.jpg HTTP/1.1[0m" 304 -
2025-10-14 16:28:25,743 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:25] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:28:25,746 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:28:25] "[36mGET /static/img/team_ciso.jpg HTTP/1.1[0m" 304 -
2025-10-14 16:30:46,702 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:30:46] "GET / HTTP/1.1" 200 -
2025-10-14 16:30:46,751 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:30:46] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:30:46,759 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:30:46] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:32:03,626 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:03] "GET /auth/login HTTP/1.1" 200 -
2025-10-14 16:32:03,682 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:03] "[36mGET /static/css/style.css HTTP/1.1[0m" 304 -
2025-10-14 16:32:03,688 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:03] "[36mGET /static/js/app.js HTTP/1.1[0m" 304 -
2025-10-14 16:32:35,966 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:35] "GET / HTTP/1.1" 200 -
2025-10-14 16:32:36,013 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:36] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 16:32:36,019 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:36] "GET /static/js/app.js HTTP/1.1" 200 -
2025-10-14 16:32:36,066 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:36] "GET /static/img/favicon.ico HTTP/1.1" 200 -
2025-10-14 16:32:37,438 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:37] "GET / HTTP/1.1" 200 -
2025-10-14 16:32:37,476 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:37] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 16:32:37,480 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:37] "GET /static/js/app.js HTTP/1.1" 200 -
2025-10-14 16:32:37,517 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:37] "GET /static/img/favicon.ico HTTP/1.1" 200 -
2025-10-14 16:32:38,945 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:38] "GET / HTTP/1.1" 200 -
2025-10-14 16:32:39,024 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:39] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 16:32:39,026 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:39] "GET /static/js/app.js HTTP/1.1" 200 -
2025-10-14 16:32:39,058 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:39] "GET /static/img/favicon.ico HTTP/1.1" 200 -
2025-10-14 16:32:41,507 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:41] "GET / HTTP/1.1" 200 -
2025-10-14 16:32:41,550 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:41] "GET /static/css/style.css HTTP/1.1" 200 -
2025-10-14 16:32:41,560 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:41] "GET /static/js/app.js HTTP/1.1" 200 -
2025-10-14 16:32:41,602 [INFO] werkzeug: 192.168.0.101 - - [14/Oct/2025 16:32:41] "GET /static/img/favicon.ico HTTP/1.1" 200 -
2025-10-15 22:49:33,310 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-15 22:49:33,315 [ERROR] app: Failed to run Base.metadata.create_all()
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
    ~~~~~~~~~~~~~^
        exc_value,
        ^^^^^^^^^^
        with_traceback=exc_tb,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/core/database.py", line 39, in init_db
    Base.metadata.create_all(DB_ENGINE)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/sql/schema.py", line 4930, in create_all
    bind._run_ddl_visitor(
    ~~~~~~~~~~~~~~~~~~~~~^
        ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 341, in _run_ddl_visitor
    with self.begin() as conn:
         ~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 379, in begin
    with self.connect() as conn:
         ~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, dialect, self
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
    ~~~~~~~~~~~^
        sqlalchemy_exception, with_traceback=exc_info[2], from_=e
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
    ~~~~~~~~~~~~~^
        exc_value,
        ^^^^^^^^^^
        with_traceback=exc_tb,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2025-10-15 22:49:33,319 [INFO] app: Database initialized (url=sqlite:////var/www/html/bankapp/data/bankapp.sqlite3, echo=False)
2025-10-15 22:49:33,886 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.33.0.2:5000
2025-10-15 22:49:33,886 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-10-15 22:49:33,887 [INFO] werkzeug:  * Restarting with stat
2025-10-15 22:49:34,067 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-15 22:49:34,070 [ERROR] app: Failed to run Base.metadata.create_all()
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
    ~~~~~~~~~~~~~^
        exc_value,
        ^^^^^^^^^^
        with_traceback=exc_tb,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/core/database.py", line 39, in init_db
    Base.metadata.create_all(DB_ENGINE)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/sql/schema.py", line 4930, in create_all
    bind._run_ddl_visitor(
    ~~~~~~~~~~~~~~~~~~~~~^
        ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 341, in _run_ddl_visitor
    with self.begin() as conn:
         ~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 379, in begin
    with self.connect() as conn:
         ~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, dialect, self
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
    ~~~~~~~~~~~^
        sqlalchemy_exception, with_traceback=exc_info[2], from_=e
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
    ~~~~~~~~~~~~~^
        exc_value,
        ^^^^^^^^^^
        with_traceback=exc_tb,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2025-10-15 22:49:34,074 [INFO] app: Database initialized (url=sqlite:////var/www/html/bankapp/data/bankapp.sqlite3, echo=False)
2025-10-15 22:49:34,087 [WARNING] werkzeug:  * Debugger is active!
2025-10-15 22:49:34,090 [INFO] werkzeug:  * Debugger PIN: 598-131-607
2025-10-17 18:08:25,020 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-17 18:08:25,028 [ERROR] app: Failed to run Base.metadata.create_all()
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
    ~~~~~~~~~~~~~^
        exc_value,
        ^^^^^^^^^^
        with_traceback=exc_tb,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/core/database.py", line 39, in init_db
    Base.metadata.create_all(DB_ENGINE)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/sql/schema.py", line 4930, in create_all
    bind._run_ddl_visitor(
    ~~~~~~~~~~~~~~~~~~~~~^
        ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 341, in _run_ddl_visitor
    with self.begin() as conn:
         ~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 379, in begin
    with self.connect() as conn:
         ~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, dialect, self
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
    ~~~~~~~~~~~^
        sqlalchemy_exception, with_traceback=exc_info[2], from_=e
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
    ~~~~~~~~~~~~~^
        exc_value,
        ^^^^^^^^^^
        with_traceback=exc_tb,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2025-10-17 18:08:25,035 [INFO] app: Database initialized (url=sqlite:////var/www/html/bankapp/data/bankapp.sqlite3, echo=False)
2025-10-17 18:08:25,570 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.33.0.2:5000
2025-10-17 18:08:25,570 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-10-17 18:08:25,571 [INFO] werkzeug:  * Restarting with stat
2025-10-17 18:08:25,778 [INFO] core.logger: Logging configured with fallback (file=../bankapp/logs/app.log)
2025-10-17 18:08:25,783 [ERROR] app: Failed to run Base.metadata.create_all()
Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
    ~~~~~~~~~~~~~^
        exc_value,
        ^^^^^^^^^^
        with_traceback=exc_tb,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/core/database.py", line 39, in init_db
    Base.metadata.create_all(DB_ENGINE)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/sql/schema.py", line 4930, in create_all
    bind._run_ddl_visitor(
    ~~~~~~~~~~~~~~~~~~~~~^
        ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 341, in _run_ddl_visitor
    with self.begin() as conn:
         ~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 379, in begin
    with self.connect() as conn:
         ~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, dialect, self
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
    ~~~~~~~~~~~^
        sqlalchemy_exception, with_traceback=exc_info[2], from_=e
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
    ~~~~~~~~~~~~~^
        exc_value,
        ^^^^^^^^^^
        with_traceback=exc_tb,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/d3s0lxt3/Projects/University/OS/bankapp/venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2025-10-17 18:08:25,786 [INFO] app: Database initialized (url=sqlite:////var/www/html/bankapp/data/bankapp.sqlite3, echo=False)
2025-10-17 18:08:25,801 [WARNING] werkzeug:  * Debugger is active!
2025-10-17 18:08:25,803 [INFO] werkzeug:  * Debugger PIN: 887-791-854
